### ISSUE TITLE
device_state_attributes is no longer permitted starting with 2021.12

### ISSUE THREAD

**Issue by iridris** [TarheelGrad1998/files#11]
The beta of 2021.12 is now flagging this custom component for using `device_state_attributes`. 

The full text of the warning:
`2021-12-09 18:35:46 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gallery_images (<class 'custom_components.files.sensor.FilesSensor'>) implements device_state_attributes. Please report it to the custom component author.
`

I believe this is the relevant change from a few months ago: https://github.com/home-assistant/core/pull/47304

**Comment by TarheelGrad1998** [comment]
Thanks for reporting.  Will fix

**Comment by TarheelGrad1998** [comment]
Somehow I thought that would be more complicated...

Anyway, fix is in.  Can you apply it to your beta and let me know if it's fixed now?
