### ISSUE TITLE
Service for reloading the images

### ISSUE THREAD

**Issue by Kaibob2** [TarheelGrad1998/files#6]
Hi!
Great component in connection with the gallery card. I was looking for something quite long. I have one suggestion which would be quite useful, i think.
I have a script which takes a snapshot from a camera. This snapshot get's saved in a folder to which the file sensor points.
Before i used your component i created a persistent message which directly showed the taken snapshot.
Now the saved snapshot resides unseen in the folder until the next update of the file sensor.
Would it be possible to integrate a service (which i canthen call from the script which takes the snapshot) to update the file sensor and make the snapshot visible directly after storing it?

Best regards
Kai

**Comment by djo4ever** [comment]
hi,
it seems you can do:
service: homeassistant.update_entity
data: {}
target:
  entity_id: sensor.gallery_images

**Comment by TarheelGrad1998** [comment]
Thanks, @djo4ever!  If someone confirms this works, I'll update the documentation.

**Comment by TarheelGrad1998** [comment]
Someone already confirmed this worked in the [thread here]( https://community.home-assistant.io/t/gallery-panel-for-images-videos/122571/129?u=tarheelgrad1998). 

I'll update the documentation and close this issue.
